// -*- mode:C++; tab-width:8; c-basic-offset:2; indent-tabs-mode:nil -*-
#pragma once

#include <iostream>

inline void vector_bench_usage(std::ostream& out) {
  out << "usage: ceph-vector-bench -f <fvecs_file> -p <pool> [options]\n"
      << "       ceph-vector-bench -f <fvecs_file> --verify-only [options]\n"
      << "       ceph-vector-bench --recall -f <base.fvecs> -p <pool> -q <query.fvecs> --gt <gt.ivecs> [options]\n"
      << "\n"
      << "Load: Load SIFT/fvecs into Ceph with LSH-based PG placement.\n"
      << "Verify: Measure if similar vectors land in same PG (no Ceph needed).\n"
      << "Recall: LSH Recall vs Ground Truth (multi-table Fan-out, requires Ceph + loaded data).\n"
      << "\n"
      << "required (load): -f, -p\n"
      << "required (verify): -f, --verify-only\n"
      << "required (recall): -p, -q, --gt, --pg-num, -f (base .fvecs for local lookup)\n"
      << "\n"
      << "  -f, --file <file>     .fvecs input (e.g. sift_base.fvecs)\n"
      << "  -p, --pool <pool>     target pool (load/recall)\n"
      << "  -q, --query <file>    query .fvecs for recall (e.g. sift_query.fvecs)\n"
      << "  --verify-only        verify LSH locality, no Ceph connection\n"
      << "  --recall             measure single-PG Recall vs ground truth\n"
      << "  --num-tables <N>     LSH tables for Fan-out (default: 128). Load/Recall.\n"
      << "  --table-set-size <N> split tables into sets (e.g. 16 with 32 tables => 2 sets)\n"
      << "  --write-top-pgs <N>  load: per-vector PG votes top-N only (0=all unique PGs)\n"
      << "  --write-top-pgs-per-set <N> load: per set top-N PGs (default: 1)\n"
      << "  --pg-map-mode <m>    PG mapping mode: stable|mixed (default: stable)\n"
      << "  --hash-backend <m>   table backend: lsh|orth-sign|rotation|faiss_rotation|rotation_repr1|annoy|pivot|hybrid (default: lsh)\n"
      << "  --pivot-build-sample <N> pivot training sample count for farthest-first reps (default: 4096)\n"
      << "  --pivot-probe-budget <N> pivot candidate budget before final top-N cut (default: 8)\n"
      << "  --hybrid-lsh-vote-topk <N> hybrid: keep top-N LSH-voted PGs before rerank (default: 8)\n"
      << "  --hybrid-pivot-topk <N> hybrid: keep top-N pivot PGs before fusion (default: 4)\n"
      << "  --rot-seed <N>       orth-sign/rotation seed (default: 1315423911)\n"
      << "  --hash-bits <N>      hash bit-width [1..32], 0=auto from pg_num (default: 0)\n"
      << "  --hash-repeat-rounds <N> repeated hash rounds (orth-sign, default: 1)\n"
      << "  --repeat-seed-stride <N> per-round seed stride (default: 2654435761)\n"
      << "  --repeat-select-single-pg force top-1 PG selection after repeat voting\n"
      << "  --rotation-use-dims <N> use first N rotated dims for bucket mapping (default: 4)\n"
      << "  --rotation-bins-per-dim <N> coarse bins per rotated dim (default: 8)\n"
      << "  --rotation-min <F>   coarse quantization min value (default: -2.5)\n"
      << "  --rotation-width <F> coarse quantization bin width (default: 1.25)\n"
      << "  --rotation-neighbor-step <N> add neighboring bins within +-N steps (default: 0)\n"
      << "  --rotation-auto-calibration enable prefix-range auto calibration (default: on)\n"
      << "  --no-rotation-auto-calibration disable auto calibration and use rotation-min/width\n"
      << "  --rotation-calibration-samples <N> sampled base vectors for calibration (default: 4096)\n"
      << "  --rotation-calibration-clip-percentile <F> clip percentile [0,0.5) for robust range (default: 0.01)\n"
      << "  --verify-faiss-rotation-match compare faiss_rotation output with FAISS-compatible reference path\n"
      << "  rotation_repr1: rotate query/base with same R and route by nearest PG representative(1 per PG)\n"
      << "  annoy: rotation_repr1 representative set + annoy-style random hyperplane forest over representatives\n"
      << "  --annoy-n-trees <N>  annoy forest tree count (default: 16)\n"
      << "  --annoy-search-k <N> annoy query budget (default: 256)\n"
      << "  --annoy-leaf-size <N> annoy leaf size (default: 64)\n"
      << "  --annoy-build-sample <N> representative build sample count, 0=all (default: 0)\n"
      << "  --annoy-dist <m>     annoy distance: l2|angular (default: l2)\n"
      << "  --annoy-seed <N>     annoy RNG seed (default: 1315423911)\n"
      << "  --table-combine <m>  multi-table combine: or|and (default: or)\n"
      << "  --set-combine <m>    set-level combine: or|and (default: and)\n"
      << "  --set-replica-mode   replica set policy: none|paired|ring (default: paired)\n"
      << "  --replica-set-count  replica set count when mode=ring (default: 1)\n"
      << "  --pg-num <N>         PG count, sets LSH bits (default: 256). Load: match pool.\n"
      << "  --gt <ivecs>         ground truth (sift_groundtruth.ivecs)\n"
      << "  -n, --num <N>        limit base vectors (0=all)\n"
      << "  -Q, --query-num <N>  limit queries for recall (0=all)\n"
      << "  -o, --object-prefix  object prefix (default: vec_)\n"
      << "  -C, --create-pool    create pool (load)\n"
      << "  --probe-mode <m>     recall: union|vote (default: union)\n"
      << "  --probe-pgs <N>      recall: global top-N PGs in vote mode (legacy)\n"
      << "  --probe-pgs-per-set <N> recall: top-N PGs per set in vote mode (default: 1)\n"
      << "  --qps-mode <m>       recall qps mode: memory|end_to_end (default: memory)\n"
      << "  --warmup-queries <N> recall warmup queries in end_to_end mode (default: 0)\n"
      << "  --latency-report     print avg/p50/p95 query latency metrics\n";
}
