// -*- mode:C++; tab-width:8; c-basic-offset:2; indent-tabs-mode:nil -*-
#pragma once

#include <iostream>

inline void vector_bench_usage(std::ostream& out) {
  out << "usage: ceph-vector-bench -f <fvecs_file> -p <pool> [options]\n"
      << "       ceph-vector-bench -f <fvecs_file> --verify-only [options]\n"
      << "       ceph-vector-bench --recall -f <base.fvecs> -p <pool> -q <query.fvecs> --gt <gt.ivecs> [options]\n"
      << "\n"
      << "Load: Load SIFT/fvecs into Ceph with LSH-based PG placement.\n"
      << "Verify: Measure if similar vectors land in same PG (no Ceph needed).\n"
      << "Recall: LSH Recall vs Ground Truth (multi-table Fan-out, requires Ceph + loaded data).\n"
      << "\n"
      << "required (load): -f, -p\n"
      << "required (verify): -f, --verify-only\n"
      << "required (recall): -p, -q, --gt, --pg-num, -f (base .fvecs for local lookup)\n"
      << "\n"
      << "  -f, --file <file>     .fvecs input (e.g. sift_base.fvecs)\n"
      << "  -p, --pool <pool>     target pool (load/recall)\n"
      << "  -q, --query <file>    query .fvecs for recall (e.g. sift_query.fvecs)\n"
      << "  --verify-only        verify LSH locality, no Ceph connection\n"
      << "  --recall             measure single-PG Recall vs ground truth\n"
      << "  --num-tables <N>     LSH tables for Fan-out (default: 128). Load/Recall.\n"
      << "  --table-set-size <N> split tables into sets (e.g. 16 with 32 tables => 2 sets)\n"
      << "  --write-top-pgs <N>  load: per-vector PG votes top-N only (0=all unique PGs)\n"
      << "  --write-top-pgs-per-set <N> load: per set top-N PGs (default: 1)\n"
      << "  --pg-map-mode <m>    PG mapping mode: stable|mixed (default: stable)\n"
      << "  --hash-backend <m>   table hash backend: lsh|orth-rot (default: lsh)\n"
      << "  --rot-seed <N>       orth-rot seed (default: 1315423911)\n"
      << "  --hash-bits <N>      hash bit-width [1..32], 0=auto from pg_num (default: 0)\n"
      << "  --hash-repeat-rounds <N> repeated hash rounds (orth-rot, default: 1)\n"
      << "  --repeat-seed-stride <N> per-round seed stride (default: 2654435761)\n"
      << "  --repeat-select-single-pg force top-1 PG selection after repeat voting\n"
      << "  --table-combine <m>  multi-table combine: or|and (default: or)\n"
      << "  --set-combine <m>    set-level combine: or|and (default: and)\n"
      << "  --set-replica-mode   replica set policy: none|paired|ring (default: paired)\n"
      << "  --replica-set-count  replica set count when mode=ring (default: 1)\n"
      << "  --pg-num <N>         PG count, sets LSH bits (default: 256). Load: match pool.\n"
      << "  --gt <ivecs>         ground truth (sift_groundtruth.ivecs)\n"
      << "  -n, --num <N>        limit base vectors (0=all)\n"
      << "  -Q, --query-num <N>  limit queries for recall (0=all)\n"
      << "  -o, --object-prefix  object prefix (default: vec_)\n"
      << "  -C, --create-pool    create pool (load)\n"
      << "  --probe-mode <m>     recall: union|vote (default: union)\n"
      << "  --probe-pgs <N>      recall: global top-N PGs in vote mode (legacy)\n"
      << "  --probe-pgs-per-set <N> recall: top-N PGs per set in vote mode (default: 1)\n";
}
